<a href="https://colab.research.google.com/github/LeyvinoBezerra/API-de-Consulta/blob/main/Aula_4_Amostragem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Montagem de Drive

In [ ]:
#monte o drive caso precise usar/salvar arquivos do seu drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#mude o ponto de execução para outro diretório, caso deseje
%cd /content/drive/MyDrive/Colab Notebooks/AprendizadoMaquina

/content/drive/MyDrive/Colab Notebooks/AprendizadoMaquina

[Dataset retirado daqui](https://www.kaggle.com/vvenanccio/irisflowers)

In [ ]:
# dfIris = pd.read_csv('./bases/iris.csv')

## Amostragem de Dados

In [ ]:
import pandas as pd

In [ ]:
from sklearn.datasets import load_iris
data = load_iris()
df = pd.DataFrame(data=data.data, columns=data.feature_names)
df['class'] = pd.Series(data.target)
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [ ]:
#dfIris = df.rename(columns={"sepal length (cm)":"sepallenght","sepal width (cm)":"sepalwidth", "petal length (cm)":"petallength","petal width (cm)":"petalwidth","target":"class"})

In [ ]:
dfIris = df.copy()
dfIris

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [ ]:
dfIris['class'].value_counts().round()

class
0    50
1    50
2    50
Name: count, dtype: int64

## 1) Treino e teste - Holdout

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [ ]:
from sklearn.model_selection import train_test_split

**train_test_split** divide o conjunto de dados em 4 subconjuntos:

1.   Conjunto com as entradas para treino (X_train)
2.   Conjunto com as entradas para teste (X_test)
3.   Conjunto com as saídas do treino (y_train)
4.   Conjunto com as saídas do teste (y_test)

São passados como parâmetros: as colunas de entrada, a coluna alvo (saída) e o tamanho do conjunto de teste (percentual), observe que quando colocamos 0.33, estamos informando que o conjunto de teste será 1/3 do dataset total

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dfIris.drop(columns=['class']), dfIris['class'],test_size=0.33)
X_test.shape

(50, 4)

random state: Uma semente aleatória é qualquer número ou vector usado para inicializar um gerador de números pseudo-aleatórios que, por sua vez, é um **algoritmo determinístico** para gerar números cujas sequências são aproximadamente as que se iriam esperar de números (verdadeiramente, enfatize-se) aleatórios.

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(dfIris.drop(columns=['class']), dfIris['class'],test_size=0.33,random_state =12)
X_train

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
132                6.4               2.8                5.6               2.2
85                 6.0               3.4                4.5               1.6
52                 6.9               3.1                4.9               1.5
63                 6.1               2.9                4.7               1.4
48                 5.3               3.7                1.5               0.2
..                 ...               ...                ...               ...
76                 6.8               2.8                4.8               1.4
3                  4.6               3.1                1.5               0.2
130                7.4               2.8                6.1               1.9
134                6.1               2.6                5.6               1.4
75                 6.6               3.0                4.4               1.4

[100 rows x 4 columns]

In [ ]:
y_train.value_counts()

class
2    38
1    36
0    26
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

class
0    24
1    14
2    12
Name: count, dtype: int64

Observe que não há garantia de que se mantenha a proporção original de exemplos em cada classe

Para ter essa garantia, usamos o parâmetro **stratify** e passamos a coluna alvo

In [ ]:
#Usando o parâmetro stratify para dividir os dados de forma a manter a proporção de exemplos por classe semelhante à proporção original (do dataset completo)
X_train, X_test, y_train, y_test = train_test_split(dfIris.drop(columns=['class']), dfIris['class'],test_size=0.33, stratify=dfIris['class'])

In [ ]:
y_train.value_counts()

class
2    34
0    33
1    33
Name: count, dtype: int64

In [ ]:
y_test.value_counts()

class
0    17
1    17
2    16
Name: count, dtype: int64

## Amostragem Aleatória

Para executarmos a **amostragem aleatória**, executamos N vezes o train_test_split (N holdouts)

In [ ]:
#Usando o parâmetro stratify para dividir os dados de forma a manter a proporção de exemplos por classe semelhante à proporção original (do dataset completo)
X_train1, X_test1, y_train1, y_test1 = train_test_split(dfIris.drop(columns=['class']), dfIris['class'],test_size=0.33, stratify=dfIris['class'])
X_train2, X_test2, y_train2, y_test2 = train_test_split(dfIris.drop(columns=['class']), dfIris['class'],test_size=0.33, stratify=dfIris['class'])
X_train3, X_test3, y_train3, y_test3 = train_test_split(dfIris.drop(columns=['class']), dfIris['class'],test_size=0.33, stratify=dfIris['class'])

## 2) Validação cruzada

O sklearn possui várias estratégias para executarmos a validação cruzada, as principais são:

Validação do Modelo:

* [cross_val_score](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html#sklearn.model_selection.cross_val_score): Retorna um array com o resultado da métrica escolhida para cada fold. Só permite 1 métrica (default é acurácia para classificação e r2 para regressão)
* [cross_validate](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_validate.html#sklearn.model_selection.cross_validate): Retorna um dicionário com os arrays das métricas escolhidas para cada fold, bem como os tempos de treino e teste.  Permite a definição de múltiplas métricas (usamos o make_scorer para isso)
* [cross_val_predict](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_predict.html#sklearn.model_selection.cross_val_predict): Retorna a predição de cada amostra para quando ela esteve no conjunto de teste.

Classes do Divisor:

* [KFold](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html#sklearn.model_selection.KFold): Retorna as listas com os índices de cada fold separado (não faz a estratificação por classe).
* [StratifiedKFold](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html#sklearn.model_selection.StratifiedKFold): Retorna as listas com os índices de cada fold separado, estratificando por classe, ou seja, mantendo a mesma proporção de amostras por classe que a base completa possui.
* [ShuffleSplit]: sorteia aleatoriamente índices de treino e teste em cada divisão. Não há garantia de que: todos os elementos apareçam no teste, ou
 apareçam o mesmo número de vezes.

### Testando o parâmetro Shuffle na divisão dos Folds

o Kfold e o StratifiedKFold não embaralham por padrão as amostras, o que faz com que todas as vezes que ele for executado, faça a mesma divisão **(observe pelo exemplo abaixo)**

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.StratifiedKFold.html#

In [ ]:
from sklearn.model_selection import StratifiedKFold
X = dfIris.drop(columns=['class'])
y = dfIris['class']

In [ ]:
skf = StratifiedKFold(n_splits=5)
for train_index, test_index in skf.split(X, y):
  print("TEST:", test_index)

TEST: [  0   1   2   3   4   5   6   7   8   9  50  51  52  53  54  55  56  57
  58  59 100 101 102 103 104 105 106 107 108 109]
TEST: [ 10  11  12  13  14  15  16  17  18  19  60  61  62  63  64  65  66  67
  68  69 110 111 112 113 114 115 116 117 118 119]
TEST: [ 20  21  22  23  24  25  26  27  28  29  70  71  72  73  74  75  76  77
  78  79 120 121 122 123 124 125 126 127 128 129]
TEST: [ 30  31  32  33  34  35  36  37  38  39  80  81  82  83  84  85  86  87
  88  89 130 131 132 133 134 135 136 137 138 139]
TEST: [ 40  41  42  43  44  45  46  47  48  49  90  91  92  93  94  95  96  97
  98  99 140 141 142 143 144 145 146 147 148 149]

Se quiser alterar esse comportamento, coloque shuffle = True

In [ ]:
skf = StratifiedKFold(n_splits=5, shuffle=True)
for train_index, test_index in skf.split(X, y):
  print("TEST:", test_index)

TEST: [ 10  11  13  15  17  21  23  28  29  41  54  57  61  65  69  75  76  78
  89  96 102 111 117 118 125 127 129 132 139 149]
TEST: [  1   4   5   6   9  22  35  39  48  49  63  64  70  71  72  73  85  91
  95  98 104 108 120 134 138 140 142 144 147 148]
TEST: [  0   2   3   7   8  32  33  40  43  47  51  53  56  59  66  67  87  92
  94  97 103 113 119 123 126 128 131 135 137 146]
TEST: [ 12  14  16  19  24  25  26  27  37  45  50  52  58  60  62  79  81  84
  88  99 100 105 106 109 110 116 122 130 133 136]
TEST: [ 18  20  30  31  34  36  38  42  44  46  55  68  74  77  80  82  83  86
  90  93 101 107 112 114 115 121 124 141 143 145]

In [ ]:
from sklearn.model_selection import ShuffleSplit

shu = ShuffleSplit(n_splits=5)
for train_index, test_index in shu.split(X, y):
  print("TEST:", test_index)

TEST: [149 123  92  19  30  76   7   5  24  11   8  27 140 115 117]
TEST: [127  40 138  99 131  53 117  49  34   1 128  44  58  79 104]
TEST: [ 15  50  58 103 148  87  11  16 113   5  89  72  61 118 124]
TEST: [ 73 122   5  61  22  93 132  26  32  12 135 102  19  38  31]
TEST: [ 44  35  69  49 108  33  42  65  95   5  92 147  43  12  31]

#### Usando cross_val_score

In [ ]:
from sklearn.model_selection import KFold, StratifiedKFold, ShuffleSplit, RepeatedStratifiedKFold
from sklearn.model_selection import cross_val_score,cross_val_predict
kfold = KFold(n_splits=5)
skfold = StratifiedKFold(n_splits=5, shuffle= False) #experimente tirar shuffle=True

In [ ]:
#algoritmo de classificação que será usado
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [ ]:
# Experimente trocar por cv=kfold ou skfold com shuffle=True

score = cross_val_score(knn, dfIris.drop(columns=['class']), dfIris['class'], cv=skfold)
print(score)
print("media do score:" , score.mean())

[0.96666667 1.         0.93333333 0.96666667 1.        ]
media do score: 0.9733333333333334

#### Usando cros_val_predict

In [ ]:
#usando a função cross_val_predict
pred = cross_val_predict(knn, dfIris.drop(columns=['class']), dfIris['class'], cv=skfold)
print(pred)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1
 1 1 1 2 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]